### ISSUE TITLE
Categories / Default Categories

### ISSUE THREAD

**Issue by jessie129j** [whaleap/during-budget#114]
# Description
사용자 카테고리 목록에 기본 카테고리 추가

**기본 카테고리 종류**
- 수입 기타(💰)
- 지출 기타(💸)
  
**고려사항**
- 카테고리 모델에 isDefault 필드 추가
- 기본 카테고리는 수정 및 삭제 불가능
- GET /users/current 또는 GET /categories API의 결과에서 항상 마지막 순서에 배치
  => 기본 카테고리를 users.cateogires의 마지막에 배치하고 새로운 카테고리가 추가될 때 기본 카테고리 앞에 끼워넣는 방식 

**Todo**
- [x] 개발
- [x] 기존 도큐먼트에 기본 카테고리 삽입

**Comment by jessie129j** [comment]
> @navynj: 이모티콘은 돈으로 하면 월급이랑 헷갈릴 거 같고 영수증 같은 게 적당할듯?

이 부분을 놓쳤다 아이콘을 빼거나 다른걸로 다시 설정해야 할 것 같다...!
추천 부탁드립니다!!

**수입 기타** 이모티콘 후보
1. 💰(현재)
2. 🧾
3. 🏷️
4. ➕
5. (no emoticon)

**지출 기타** 이모티콘 후보
1. 💸(현재)
2. 🏷️
3. ➖
4. (no emoticon)

**Comment by navynj** [comment]
@jessie129j 
아이콘을 빼는 거 괜찮을 거 같습니다! 
기획하다보니 기본 카테고리보단 '카테고리 없음' 개념에 가까워졌다.

### 참고 - [디자인 리뉴얼](https://www.figma.com/file/XwarAUY8gbGfxx4NfVeNR3/During-Budget?node-id=0%3A1&t=BDsJ3M1RKZ3OQYwk-0)
<img width="254" alt="image" src="https://user-images.githubusercontent.com/82319291/218314185-0dc83b20-3957-4bd8-a9bb-2b4a979f00b4.png"> <img width="253" alt="image" src="https://user-images.githubusercontent.com/82319291/218314213-47cc6e76-3ae8-4320-918d-0769a7ea7839.png">

기본 예산 설정 과정을 대폭 수정중인데, 이런 식으로 전체 목표 > 카테고리별 예산계산할 수 있게 할 예정이야.
여기서 '남는 금액'이 기본 카테고리에 들어가게 될 거 같다.
(+ 남는 금액이 음수이면, 즉 전체 목표를 초과하면 에러로 막을 예정~)

**Comment by jessie129j** [comment]
@navynj 질문 있습니다!

그럼 예를 들어서 예산을

지출 예산 총합: 10000
식비 카테고리 예산: 2000
교통비 카테고리 예산:2000
이렇게 설정하면

1 
기본 카테고리 예산: 6000 
이렇게 자동으로 설정되어야 하는건가요?

2. 그럼 사용자는 예산 설정할 때
기본 카테고리 예산: 2000
이렇게 자기가 기본 카테고리에 대해 예산을 설정할 수 없어야 하나요?

3. 여전히 사용자는 기본 카테고리에 대한 트랜젝션을 추가할 수 있나요? 그럼 화면에서 보이는 남는 금액은 
기본 카테고리의 amountPlanned - 기본 카테고리의 amountCurrent
가 되어야 하는건가요?

**Comment by navynj** [comment]
@jessie129j 

1. 맞습니다 - 기본카테고리보단 미분류라는 명칭이 맞을 것 같음. 분류되지 않은 목표 금액이 6000으로 자동설정 되어야한다
2. 이 부분은 까다로운데, '미분류' 개념으로 생각할 경우 목표 금액은 설정할 수 없는 게 맞다. 라고 결론내렸습니다!
3. 네! 분류 없는 트랜잭션 추가가 가능합니다(예정 / 거래)
    '화면에 보이는 남는 금액'이 어떤 화면인지 모르겠습니다!! 기본 예산 설정 화면인가요? 카테고리 차트 화면인가요?

**Comment by navynj** [comment]
아앗 바로 위에 저 커밋 푸시했다는 알림은,. 내 리베이스로 인해... 푸시된 것,..
앞으로는 메인에 올린 것은 리베이스하지 않겠습니다,....

**Comment by jessie129j** [comment]
> 아앗 바로 위에 저 커밋 푸시했다는 알림은,. 내 리베이스로 인해... 푸시된 것,.. 앞으로는 메인에 올린 것은 리베이스하지 않겠습니다,....

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ알겠슴니다!

**Comment by jessie129j** [comment]
>    '화면에 보이는 남는 금액'이 어떤 화면인지 모르겠습니다!! 기본 예산 설정 화면인가요? 카테고리 차트 화면인가요?
>    위 코멘트에서 추가한 화면 즉 기본예산 설정 화면의 경우 트랜잭션이 아닌 '목표'만 다룹니다.
>    따라서 화면에 보이는 남는 금액은 항상 [전체 목표 - 현재 카테고리 목표]가 됩니다.

@navynj 아하 그럼 [전체 목표 - 현재 카테고리 목표]가 [미분류 목표 금액]과 동일한게 맞나요?

**Comment by navynj** [comment]
@jessie129j 
맞습니다 정확하다~!
