### ISSUE TITLE
Category / Fetch categories from server

### ISSUE THREAD

**Issue by navynj** [whaleap/during-budget#46]
- Load category data
- Update budget/category structure
    - move amount data from category to budget

**Comment by earlyoonj** [comment]
# Working Log
- Lazy loading multiple requests
    - use def in loader function
    - <Await>, <Suspense>
    - ErrorElement - useAsyncError

**Comment by earlyoonj** [comment]
- Fetch Data
![Image](https://user-images.githubusercontent.com/82319291/215258556-104f9262-7c54-4dd5-aabc-4afd5d40759d.png)
